env:
  browser: true
  commonjs: true
  es2020: true
parserOptions:
  ecmaVersion: 11
rules:
  jsdoc/check-alignment: 1
  jsdoc/check-examples: 1
  jsdoc/check-indentation: 1
  jsdoc/check-param-names: 1
  jsdoc/check-syntax: 1
  jsdoc/check-tag-names: 1
  jsdoc/check-types: 1
  jsdoc/implements-on-classes: 1
  jsdoc/match-description: 1
  jsdoc/newline-after-description: 1
  jsdoc/require-description: 1
  jsdoc/require-description-complete-sentence: 1
  jsdoc/require-hyphen-before-param-description: 1
  jsdoc/require-jsdoc: 1
  jsdoc/require-param: 1
  jsdoc/require-param-description: 1
  jsdoc/require-param-name: 1
  jsdoc/require-param-type: 1
  jsdoc/require-returns: 1
  jsdoc/require-returns-check: 1
  jsdoc/require-returns-type: 1
  jsdoc/valid-types: 1
plugins:
  - jsdoc
settings:
  jsdoc:
    mode: typescript