#!/usr/bin/env node

const program = require("commander")
const path = require("path")
const fs = require("fs")
const yaml = require("yaml")
const prettier = require("prettier")
const sass = require("sass")
const pather = require("../lib/pather/index")
const stylesheet = require("../lib/stylesheet")

const log = console.info
const error = console.error

program
    .usage("[file] [options]")
    .option("-s, --scss", "Scss stylesheet")
    .option("-c, --css", "CSS stylesheet")
    .parse(process.argv)

;(async () => {
    try {
        let defaultFile = path.join(
            __dirname,
            "..",
            "..",
            "config",
            "preons.yaml"
        )

        let file = pather.getAbsolute(program.args[0] || defaultFile)

        let contents = fs.readFileSync(file, "utf8")
        let set = yaml.parse(contents)

        log(stylesheet({ set, outType: program["scss"] ? 'scss' : 'css' }))
    } catch (e) {
        error(e.message)
    }
})()
