#!/usr/bin/env node

const program = require("commander");
const toTable = require("markdown-table");
const { exec } = require("child_process");
const util = require("util");
const pExec = util.promisify(exec);
const strip = require("strip-indent");

const log = console.info;
const error = console.error;

program.parse(process.argv);

(async () => {
  try {
    let { stdout } = await pExec("preons config");
    let set = JSON.parse(stdout);

    let tables = Object.keys(set.preons.properties)
      .filter((property) => set.preons.properties[property])
      .map((property, index) => {
        let mappings = Object.entries(
          set.preons.properties[property].mappings
        ).reduce(
          (acc, entry) => {
            acc.push([...entry]);
            return acc;
          },
          [["class", "value"]]
        );
        let table = toTable(mappings);
        return strip(`### ${property}

        ${table}`);
      })
      .map((i) => strip(i).replace(/[\s]+\|/, "\n\n|"));

    log(tables.join("\n\n"));
  } catch (e) {
    error(e.message);
  }
})();
