#!/usr/bin/env node

const program = require("commander")
const fs = require("fs")
const path = require("path")
const translate = require("../lib/translate/index")
const yaml = require("yaml")
const pather = require("../lib/pather/index")

const log = console.info
const error = console.error

program.parse(process.argv)
;(async () => {
    try {
        let defaultFile = path.join(
            __dirname,
            "..",
            "..",
            "config",
            "preons.yaml"
        )

        let file = pather.getAbsolute(program.args[0] || defaultFile)

        let contents = fs.readFileSync(file, "utf8")

        let translated = await translate(contents)

        log(yaml.stringify(translated))
    } catch (e) {
        error(e.message)
    }
})()
